my_blog/apps/blog/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views
from .views import *

app_name = 'blog'
urlpatterns = [
    url(r'^index/$',views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$',views.PostDetailView.as_view(), name= 'detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^article/$', views.article, name='article'),
    url(r'^resource/$',views.resource,name='resource'),
    url(r'^timeline/$',views.timeLine,name='timeLine'),
    url(r'^about/$',views.about, name='about'),

]
handler404 = page_not_found
handler403 = permission_denied
handler500 = page_error

my_blog/apps/comments/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views


app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<article_pk>[0-9]+)/$', views.get_comment, name='get_comment'),
]

my_blog/my_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'', include('comments.urls', namespace='comments')),
    #url(r'^search/', include('haystack.urls')),
]

my_blog/apps/blog/models.py
# -*- coding:utf-8 -*-


from django.db import models
from django.urls import reverse


#作者
class Author(models.Model):
    name = models.CharField(max_length= 30)
    #email = models.CharField(blank=True)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

# 标签
class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


# 分类
class Categroy(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


# 文章
class Article(models.Model):
    title = models.CharField(max_length=50,verbose_name='标题')
    body = models.TextField(verbose_name='内容')
    created_time = models.DateTimeField(verbose_name='创建时间')
    modified_time = models.DateTimeField(verbose_name='最后修改时间')
    excerpt = models.CharField(max_length=100,blank=True,verbose_name='摘要')
    author = models.ForeignKey(Author)
    tags = models.ManyToManyField(Tag,blank=True)
    category = models.ForeignKey(Categroy)
    view = models.IntegerField(default=0,verbose_name='阅读量')

    def increase_views(self):
        self.view += 1
        self.save(update_fields=['view'])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['-created_time']

my_blog/apps/comments/models.py
# -*- coding:utf-8 -*-

from django.db import models
from blog.models import Article


class Comment(models.Model):

    name = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length= 300,blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    article = models.ForeignKey('blog.Article',on_delete=models.CASCADE)


    def __str__(self):
        return self.text[:20]

my_blog/apps/comments/forms.py
# -*- coding:utf-8 -*-

from django import forms
from .models import Comment

class CommentForms(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'text',]

my_blog/apps/blog/views.py
# -*- coding:utf-8 -*-

from django.shortcuts import render,get_object_or_404
from .models import *
from comments.forms import CommentForms
import markdown
from django.views.generic import ListView,DetailView


class IndexView(ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'post_list'


#
# def index(request):
#     post_list = Article.objects.all().order_by('-created_time')
#     return render(request,'blog/index.html',context={'post_list':post_list})

class PostDetailView(DetailView):
    model = Article
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView,self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        post.body = markdown.markdown(post.body,
                                      extensions=[
                                          'markdown.extensions.extra',
                                          'markdown.extensions.codehilite',
                                          'markdown.extensions.toc',
                                      ])
        return post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForms()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


# def detail(request, pk):
#     post = get_object_or_404(Article, pk= pk)
#     post.increase_views()
#     post.body = markdown.markdown(post.body,
#                                   extensions=[
#                                       'markdown.extensions.extra',
#                                       'markdown.extensions.codehilite',
#                                       'markdown.extensions.toc',
#                                   ])
#     form = CommentForms()
#     comment_list = post.comment_set.all()
#     context = {'post': post,
#                'form': form,
#                'comment_list': comment_list
#                }
#     return render(request, 'blog/detail.html', context=context)


# 归档
def archives(request,year, month):
    post_list = Article.objects.filter(created_time__year =year,
                                       created_time__month = month).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list':post_list})


# 分类
# def category(request, pk):
#     post = get_object_or_404(Categroy, pk= pk)
#     post_list = Article.objects.filter(category= post).order_by('-created_time')
#     return render(request,'blog/index.html', context={'post_list':post_list})


class CategoryView(ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Categroy, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


def article(request):
    post_list = Article.objects.all().order_by('-created_time')
    return render(request, 'blog/article.html', context={'post_list': post_list})


def resource(request):
    return render(request, 'blog/resource.html')


def timeLine(request):

    return render(request, 'blog/timeline.html')


def about(request):
    return render(request,'blog/about.html')


def page_not_found(request):
    return render(request,'blog/404.html')


def page_error(request):
    return render(request, '500.html')


def permission_denied(request):
    return render(request, '403.html')

my_blog/apps/comments/views.py
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Article
from .models import Comment
from .forms import CommentForms


def get_comment(request, article_pk):
    post = get_object_or_404(Article, pk=article_pk)

    if request.method == 'POST':
        form = CommentForms(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(post)

        else:
            comment_list = post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'blog/detail.html', context=context)

    return redirect(post)

my_blog/templates/50x.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>
    <title>500 &mdash; Internal Sever Error</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="description" content="Sorry, something went wrong. Internal Server Error"/>
    <style type="text/css">
        body {font-size:14px; color:#777777; font-family:arial; text-align:center; background-color: #000c2f;}
        h1 {font-size:180px; color:#99A7AF; margin: 70px 0 0 0;}
        h2 {color: #DE6C5D; font-family: arial; font-size: 20px; font-weight: bold; letter-spacing: -1px; margin: -3px 0 39px;}
        p {width:320px; text-align:center; margin-left:auto;margin-right:auto; margin-top: 30px }
        div {width:320px; text-align:center; margin-left:auto;margin-right:auto;}
        a:link {color: #34536A;}
        a:visited {color: #34536A;}
        a:active {color: #34536A;}
        a:hover {color: #34536A;}
    </style>
</head>

<body>

    <h1>500</h1>
    <h2>Internal Server Error</h2>
    <div>
        Sorry, something went wrong :(
    </div>
</body>

</html>

my_blog/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; Charset=gb2312">
    <meta http-equiv="Content-Language" content="zh-CN">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <title>一个python程序员的个人博客网站</title>
    <link rel="shortcut icon" href="{% static 'images/Logo_40.png' %}" type="image/x-icon">
    <!--Layui-->
    <link href="{% static 'plug/layui/css/layui.css' %}" rel="stylesheet" />
    <!--font-awesome-->
    <link href="{% static 'plug/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" />
    <!--全局样式表-->
    <link href="{% static 'css/global.css' %}" rel="stylesheet" />
    <!-- 代码高亮 -->
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">
    <!-- 比较好用的代码着色插件 -->
    <link href="{% static 'css/prettify.css' %}" rel="stylesheet" />

     {% block head %}
    {% endblock head %}
</head>
<body>
    <!-- 导航 -->
    <nav class="blog-nav layui-header">
        <div class="blog-container">
            <!-- QQ互联登陆 -->
            <a href="javascript:;" class="blog-user">
                <i class="fa fa-qq"></i>
            </a>
            <a href="javascript:;" class="blog-user layui-hide">
                <img src="{% static 'images/Absolutely.jpg' %}" alt="Absolutely" title="Absolutely" />
            </a>
            <!-- 不落阁 -->
            <a class="blog-logo" href="{% url 'blog:index' %}">骑着小毛驴</a>
            <!-- 导航菜单 -->
            <ul class="layui-nav" lay-filter="nav">
                <li class="layui-nav-item layui-this">
                    <a href="{% url 'blog:index' %}"><i class="fa fa-home fa-fw"></i>&nbsp;网站首页</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{% url 'blog:article' %}"><i class="fa fa-file-text fa-fw"></i>&nbsp;文章专栏</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{% url 'blog:resource' %}"><i class="fa fa-tags fa-fw"></i>&nbsp;资源分享</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{% url 'blog:timeLine' %}"><i class="fa fa-hourglass-half fa-fw"></i>&nbsp;点点滴滴</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{% url 'blog:about' %}"><i class="fa fa-info fa-fw"></i>&nbsp;关于本站</a>
                </li>
            </ul>
            <!-- 手机和平板的导航开关 -->
            <a class="blog-navicon" href="javascript:;">
                <i class="fa fa-navicon"></i>
            </a>
        </div>
    </nav>

                {% block main %}
                {% endblock main %}


    <!-- 底部 -->
    <footer class="blog-footer">
        <p><span>Copyright</span><span>&copy;</span><span>2018</span><a href="http://www.lyblogs.cn">前端引借</a><span>https://github.com/Leo0216/BlogTemplate</span></p>
        <p><a href="http://www.miibeian.gov.cn/" target="_blank">骑着小毛驴</a></p>
    </footer>
    <!--侧边导航-->
    <ul class="layui-nav layui-nav-tree layui-nav-side blog-nav-left layui-hide" lay-filter="nav">
        <li class="layui-nav-item layui-this">
            <a href="{% url 'blog:index' %}"><i class="fa fa-home fa-fw"></i>&nbsp;网站首页</a>
        </li>
        <li class="layui-nav-item">
            <a href="{% url 'blog:article' %}"><i class="fa fa-file-text fa-fw"></i>&nbsp;文章专栏</a>
        </li>
        <li class="layui-nav-item">
            <a href="{% url 'blog:resource' %}"><i class="fa fa-tags fa-fw"></i>&nbsp;资源分享</a>
        </li>
        <li class="layui-nav-item">
            <a href="{% url 'blog:timeLine' %}"><i class="fa fa-road fa-fw"></i>&nbsp;点点滴滴</a>
        </li>
        <li class="layui-nav-item">
            <a href="{% url 'blog:about' %}"><i class="fa fa-info fa-fw"></i>&nbsp;关于本站</a>
        </li>
    </ul>
    <!--分享窗体-->
    <div class="blog-share layui-hide">
        <div class="blog-share-body">
            <div style="width: 200px;height:100%;">
                <div class="bdsharebuttonbox">
                    <a class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                    <a class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                    <a class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                    <a class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a>
                </div>
            </div>
        </div>
    </div>
    <!--遮罩-->
    <div class="blog-mask animated layui-hide"></div>
    <!-- layui.js -->
    <script src="{% static 'plug/layui/layui.js' %}"></script>
    <!-- 全局脚本 -->
    <script src="{% static 'js/global.js' %}"></script>

    <!-- 比较好用的代码着色插件 -->
    <script src="{% static 'js/prettify.js' %}"></script>
    <!-- detial -->
    <script src="{% static 'js/detail.js' %}"></script>
    {% block footer %}
    {% endblock footer %}
</body>
</html>

my_blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags %}
    {% block head %}
    <!-- 本页样式表 -->
    <link href="{% static 'css/detail.css' %}" rel="stylesheet" />
    {% endblock head %}
    <!-- 主体（一般只改变这里的内容） -->
    {% block main %}
    <div class="blog-body">
        <div class="blog-container">
            <blockquote class="layui-elem-quote sitemap layui-breadcrumb shadow">
                <a href="{% url 'blog:index' %}" title="网站首页">网站首页</a>
                <a href="{% url 'blog:article' %}" title="文章专栏">文章专栏</a>
                <a><cite>{{ post.title }}</cite></a>
            </blockquote>
            <div class="blog-main">
                <div class="blog-main-left">
                    <!-- 文章内容（使用Kingeditor富文本编辑器发表的） -->
                    <div class="article-detail shadow">
                        <div class="article-detail-title">
                            {{ post.title }}
                        </div>
                        <div class="article-detail-info">
                            <span>编辑时间：{{ post.created_time }}</span>
                            <span>作者：{{ post.author.name }}</span>
                            <span>浏览量：12</span>
                        </div>
                        <div class="article-detail-content">
                            <p style="text-align:center;">
                              {{ post.body }}
                            </p>

                        </div>
                    </div>
                    <!-- 评论区域 -->
                    <div class="blog-module shadow" style="box-shadow: 0 1px 8px #a6a6a6;">
                        <fieldset class="layui-elem-field layui-field-title" style="margin-bottom:0">
                            <legend>来说两句吧</legend>
                            <div class="layui-field-box">
                                <div class="row">
                                 <form class="comment-form " action="{% url 'comments:get_comment' post.pk %}" method="post">
                                    {% csrf_token %}
                                    <div class="layui-form-item">
                                         <label for="{{ form.name.id_for_label }}">名字：</label>
                                          {{ form.name }}
                                          {{ form.name.errors }}
                                    </div>
                                     <div class="layui-form-item">
                                         <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                          {{ form.email }}
                                          {{ form.email.errors }}
                                    </div>
                                     <div class="layui-form-item">
                                         <label for="{{ form.text.id_for_label }}">评论：</label>
                                          {{ form.text }}
                                          {{ form.text.errors }}
                                         <button type="submit" class="comment-btn" >提交评论</button>
                                    </div>
                                    <!--<div class="layui-form-item">-->
                                        <!--<textarea name="editorContent" lay-verify="content" id="remarkEditor" placeholder="请输入内容" class="layui-textarea layui-hide">-->
                                            <!--{{ form.text }}-->
                                            <!--{{ form.text.errors }}-->
                                        <!--</textarea>-->
                                    <!--</div>-->
                                    <!--<div class="layui-form-item">-->
                                        <!--<button class="layui-btn" lay-submit="formRemark" lay-filter="formRemark">提交评论</button>-->
                                    <!--</div>-->
                                </form>
                                </div>
                            </div>
                        </fieldset>
                        <div class="blog-module-title">最新评论</div>
                        <ul class="blog-comment">
                            <li>
                                <div class="comment-parent">
                                    {% for comment in comment_list %}
                                    <img src="{% static 'images/Absolutely.jpg' %}" alt="" />
                                    <div class="info">
                                        <span class="username">{{ comment.name }}</span>
                                        <span class="time">{{ comment.created_time }}</span>
                                    </div>
                                    <div class="content">
                                        {{ comment.text }}
                                    </div>
                                    {% empty %}
                                    暂未评论
                                    {% endfor %}
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="blog-main-right">
                    <!--右边悬浮 平板或手机设备显示-->
                    <div class="category-toggle"><i class="fa fa-chevron-left"></i></div><!--这个div位置不能改，否则需要添加一个div来代替它或者修改样式表-->
                    <div class="article-category shadow">
                        <div class="article-category-title">分类导航</div>
                        <!-- 点击分类后的页面和artile.html页面一样，只是数据是某一类别的 -->
                        {% get_categories as category_list %}
                        {% for category in category_list %}
                        <ul>
                        <li>
                            <a href="{% url 'blog:category' category.pk  %}">{{ category.name }}<span class="post-count">(13)</span></a>
                        </li>
                        </ul>
                            {% empty %}
                            暂无分类
                            {% endfor %}
                        <div class="clear"></div>
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">相似文章</div>
                       {% get_hottest_article as articles %}
                            {% for article in articles %}
                        <ul class="fa-ul blog-module-ul">
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></li>
                        </ul>
                            {% empty %}
                            暂无文章
                            {% endfor %}
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">随便看看</div>
                        <ul class="fa-ul blog-module-ul">
                           {% get_recent_article as articles2 %}
                            {% for article in articles2%}
                        <ul class="fa-ul blog-module-ul">
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="{{ article.get_absolute_url }}" target="_blank">{{ article.title }}</a></li>

                        </ul>
                            {% empty %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    {% endblock main %}
{% block footer %}
    <!-- 本页脚本 -->
    <script src="{% static 'js/detail.js' %}"></script>
{% endblock footer %}

my_blog/templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags %}
    {% block head %}
        <!-- 本页样式表 -->
    <link href="{% static 'css/home.css' %}" rel="stylesheet" />
    {% endblock head %}
                {% block main %}
    <!-- 主体（一般只改变这里的内容） -->
    <div class="blog-body">
        <!-- canvas -->
        <canvas id="canvas-banner" style="background: #393D49;"></canvas>
        <!--为了及时效果需要立即设置canvas宽高，否则就在home.js中设置-->
        <script type="text/javascript">
            var canvas = document.getElementById('canvas-banner');
            canvas.width = window.document.body.clientWidth - 10;//减去滚动条的宽度
            if (screen.width >= 992) {
                canvas.height = window.innerHeight * 1 / 3;
            } else {
                canvas.height = window.innerHeight * 2 / 7;
            }
        </script>
        <!-- 这个一般才是真正的主体内容 -->
        <div class="blog-container">
            <div class="blog-main">
                 网站公告提示
                <div class="home-tips shadow">
                    <i style="float:left;line-height:17px;" class="fa fa-volume-up"></i>
                    <div class="home-tips-container">
                        <!--<span style="color: #009688">偷偷告诉大家，本博客的后台管理也正在制作，为大家准备了游客专用账号！</span>-->
                        <!--<span style="color: red">网站新增留言回复啦！使用QQ登陆即可回复，人人都可以回复！</span>-->
                        <!--<span style="color: red">如果你觉得网站做得还不错，来Fly社区点个赞吧！<a href="http://fly.layui.com/case/2017/" target="_blank" style="color:#01AAED">点我前往</a></span>-->
                        <!--<span style="color: #009688">不落阁 &nbsp;—— &nbsp;一个.NET程序员的个人博客，新版网站采用Layui为前端框架，目前正在建设中！</span>-->
                    </div>
                </div>
                <!--左边文章列表-->
                <div class="blog-main-left">
                    {% for post in post_list %}
                    <div class="article shadow">
                        <div class="article-left">
                            <img src="{% static 'images/cover/201703181909057125.jpg' %}" alt="文章" />
                        </div>
                        <div class="article-right">
                            <div class="article-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </div>
                            <div class="article-abstract">
                               {{ post.body }}
                            </div>
                        </div>
                        <div class="clear"></div>
                        <div class="article-footer">
                            <span><i class="fa fa-clock-o"></i>&nbsp;&nbsp;{{ post.created_time }}</span>
                            <span class="article-author"><i class="fa fa-user"></i>&nbsp;&nbsp;{{ post.author.name }}</span>
                            <span><i class="fa fa-tag"></i>&nbsp;&nbsp;<a href="#">{{ post.tag.name }}</a></span>
                            <span class="article-viewinfo"><i class="fa fa-eye"></i>&nbsp;{{ post.views }}</span>
                            <span class="article-viewinfo"><i class="fa fa-commenting"></i>&nbsp;{{ post.comment_set.count }}</span>
                        </div>
                    </div>
                    {% empty %}
                    <div class="no-post">暂时还没有发布的文章</div>
                    {% endfor %}
                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <!--<div class="pagination">-->
                    <!--<ul>-->
                        <!--<li><a href="">1</a></li>-->
                        <!--<li><a href="">...</a></li>-->
                        <!--<li><a href="">4</a></li>-->
                        <!--<li><a href="">5</a></li>-->
                        <!--<li class="current"><a href="">6</a></li>-->
                        <!--<li><a href="">7</a></li>-->
                        <!--<li><a href="">8</a></li>-->
                        <!--<li><a href="">...</a></li>-->
                        <!--<li><a href="">11</a></li>-->
                    <!--</ul>-->
                <!--</div>-->

                </div>

                <!--右边小栏目-->
                <div class="blog-main-right">
                    <div class="blogerinfo shadow">
                        <div class="blogerinfo-figure">
                            <img src="{% static 'images/Absolutely.jpg' %}" alt="Absolutely" />
                        </div>
                        <p class="blogerinfo-nickname">骑着小毛驴</p>
                        <p class="blogerinfo-introduce">一枚90后程序员，python开发工程师</p>
                        <p class="blogerinfo-location"><i class="fa fa-location-arrow"></i>&nbsp;浙江 - 台州</p>
                        <hr />
                        <div class="blogerinfo-contact">
                            <a target="_blank" title="QQ交流" href="javascript:layer.msg('启动QQ会话窗口')"><i class="fa fa-qq fa-2x"></i></a>
                            <a target="_blank" title="给我写信" href="javascript:layer.msg('启动邮我窗口')"><i class="fa fa-envelope fa-2x"></i></a>
                            <a target="_blank" title="新浪微博" href="javascript:layer.msg('转到你的微博主页')"><i class="fa fa-weibo fa-2x"></i></a>
                            <a target="_blank" title="码云" href="javascript:layer.msg('转到你的github主页')"><i class="fa fa-git fa-2x"></i></a>
                        </div>
                    </div>
                    <div></div><!--占位-->
                    <div class="blog-module shadow">
                        <div class="blog-module-title">热文排行</div>
                        {% get_hottest_article as articles %}
                            {% for article in articles %}
                        <ul class="fa-ul blog-module-ul">
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></li>
                        </ul>
                            {% empty %}
                            暂无文章
                            {% endfor %}
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">最新文章</div>
                        {% get_recent_article as articles2 %}
                            {% for article in articles2%}
                        <ul class="fa-ul blog-module-ul">
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="{{ article.get_absolute_url }}" target="_blank">{{ article.title }}</a></li>

                        </ul>
                            {% empty %}
                            {% endfor %}
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">分类</div>
                        {% get_categories as category_list %}
                        {% for category in category_list %}
                        <ul>
                        <li>
                            <a href="{% url 'blog:category' category.pk  %}">{{ category.name }}<span class="post-count">({{ category.num_posts }})</span></a>
                        </li>
                        </ul>
                        {% empty %}
                        {% endfor %}
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">归档</div>
                        {% get_file as files %}
                        {% for date in files %}
                        <ul>
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        </ul>
                        {% empty %}
                        {% endfor %}
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">友情链接</div>
                        <ul class="blogroll">
                            <li><a target="_blank" href="http://www.layui.com/" title="Layui">Layui</a></li>
                            <li><a target="_blank" href="http://www.pagemark.cn/" title="页签">页签</a></li>
                        </ul>
                    </div>
                </div>
                <div class="clear"></div>
                            </div>
        </div>
    </div>
                {% endblock main %}
    {% block footer %}
   <!-- 本页脚本 -->
    <script src="{% static 'js/home.js' %}"></script>
    {% endblock footer %}